### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by 0x61nas** [anas-elgarhy/aarty#32]
![image](https://github.com/0x61nas/aarty/assets/44965145/a3a7b643-8086-4bf3-942a-27a84e1a6635)

- [x] Remove `clap` from the dependencies (#33)
- [x] Remove `colored` and `pretty_env_logger` from the dependencies (#34)
- [x] Checkout `Cargo.lock` (c20f05bee4e2d341eec22142fa129cc531f02185)
- [ ] #100 (a.k.a. `no-std`)
- [ ] #101
- [ ] Complete the documentations
    - [x] #43
    - [x] #44
    - [x] #45
    - [ ] Create a comparison table
        - [ ] [tiv](https://github.com/radare/tiv) [speed, memory usage, features]
        - [ ] [chafa](https://hpjansson.org/chafa/)  [speed, memory usage, features]
- [x] #47
- [x] Remove the AUR submodule (46ac55bb26b2d50875b2f33a7dde3b03bf45b8ca)
- [x] Create `justfile` (e90734bbbf9c1254a569cd3da7e4d118141bec1b)
- [x] Remove some images/screenshots
- [x] #56
- [x] Implement ~`serde` feature (#35)~ ~[NEED TO FIX]~ ~`impl_serde`~ `serde` feature (#37)
- [x] Add the ability to read the image from `stdin` as mentioned in https://github.com/0x61nas/aarty/pull/6#discussion_r1006009687. (#36)
- [ ] #42
- [x] Fix the transparent handling. (ce5710b63fe28b7bd0b797e64877a9604952378f)
- [x] Fix `sym_index`. (ce5710b63fe28b7bd0b797e64877a9604952378f)
- [ ] Create tests
    - [ ] #38
    - [ ] #39
    - [ ] #102
- [x] #40
- [x] #41
- [x] Fix this https://x.com/0x61nas/status/1731994390325772631 (f7333e9)
- [ ] #55
